import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RouteGuard from "./components/RouteGuard";
import ClientLayout from "./components/ClientLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Primal_Demo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RouteGuard>
          <ClientLayout>
            {children}
          </ClientLayout>
        </RouteGuard>
      </body>
    </html>
  );
}
